export const CATEGORY_ICONS: Record<string, string> = {
  Food: 'fast-food-outline',
  'Food & Dining': 'fast-food-outline',
  Groceries: 'cart-outline',
  Grocery: 'basket-outline',
  Dining: 'restaurant-outline',
  Travel: 'airplane-outline',
  Transport: 'car-outline',
  Transportation: 'car-outline',
  Gym: 'fitness-outline',
  Fitness: 'fitness-outline',
  Water: 'water-outline',
  Internet: 'wifi-outline',
  Rent: 'home-outline',
  Home: 'home-outline',
  Housing: 'home-outline',
  Bills: 'receipt-outline',
  'Bills & Utilities': 'receipt-outline',
  Electricity: 'flash-outline',
  Gas: 'flame-outline',
  Phone: 'call-outline',
  Shopping: 'bag-outline',
  Entertainment: 'film-outline',
  Medical: 'medkit-outline',
  Health: 'medkit-outline',
  Healthcare: 'medkit-outline',
  'Health & Medical': 'medkit-outline',
  Education: 'school-outline',
  Fuel: 'flame-outline',
  EMI: 'card-outline',
  Investment: 'trending-up-outline',
  Salary: 'cash-outline',
  Income: 'cash-outline',
  Transfer: 'swap-horizontal-outline',
  Transfers: 'swap-horizontal-outline',
  Subscriptions: 'repeat-outline',
  Subscription: 'repeat-outline',
  Insurance: 'shield-outline',
  Financial: 'shield-outline',
  Refunds: 'return-down-back-outline',
  Pets: 'paw-outline',
  Clothing: 'shirt-outline',
  'Other Income': 'cash-outline',
  'Other Expenses': 'ellipsis-horizontal-outline',
  Other: 'ellipsis-horizontal-outline',
  Uncategorized: 'receipt-outline',
  Utilities: 'flash-outline',
};

export const CATEGORY_COLORS: Record<string, string> = {
  Food: '#FF6B6B',
  'Food & Dining': '#FF6B6B',
  Groceries: '#34C759',
  Grocery: '#00CEC9',
  Dining: '#FDCB6E',
  Travel: '#60A5FA',
  Transport: '#38BDF8',
  Transportation: '#38BDF8',
  Gym: '#A78BFA',
  Fitness: '#A78BFA',
  Water: '#38BDF8',
  Internet: '#38BDF8',
  Rent: '#FB923C',
  Home: '#FB923C',
  Housing: '#FB923C',
  Bills: '#F59E0B',
  'Bills & Utilities': '#F59E0B',
  Electricity: '#FDCB6E',
  Gas: '#FF6B6B',
  Phone: '#00B894',
  Shopping: '#F472B6',
  Entertainment: '#8B5CF6',
  Medical: '#FF4D4F',
  Health: '#FF4D4F',
  Healthcare: '#FF4D4F',
  'Health & Medical': '#FF4D4F',
  Education: '#6366F1',
  Fuel: '#F59E0B',
  EMI: '#636E72',
  Investment: '#00B894',
  Salary: '#00B894',
  Income: '#00B894',
  Transfer: '#B2BEC3',
  Transfers: '#B2BEC3',
  Subscriptions: '#6C5CE7',
  Subscription: '#6C5CE7',
  Insurance: '#00CEC9',
  Financial: '#00CEC9',
  Refunds: '#00B894',
  Pets: '#FDCB6E',
  Clothing: '#F472B6',
  'Other Income': '#00B894',
  'Other Expenses': '#636E72',
  Other: '#636E72',
  Uncategorized: '#636E72',
  Utilities: '#FBBF24',
};

export function getCategoryIcon(cat: string | null | undefined, defaultIcon: string = 'receipt-outline'): string {
  if (!cat) return defaultIcon;
  const key = Object.keys(CATEGORY_ICONS).find(
    (k) => k.toLowerCase().trim() === cat.toLowerCase().trim(),
  );
  return key ? CATEGORY_ICONS[key] : defaultIcon;
}

export function getCategoryColor(cat: string | null | undefined, defaultColor: string = '#6C3EF4'): string {
  if (!cat) return defaultColor;
  const key = Object.keys(CATEGORY_COLORS).find(
    (k) => k.toLowerCase().trim() === cat.toLowerCase().trim(),
  );
  return key ? CATEGORY_COLORS[key] : defaultColor;
}
