export const KEYWORD_CATEGORIES: Record<string, string> = {
  tea: 'Food & Dining',
  coffee: 'Food & Dining',
  lunch: 'Food & Dining',
  dinner: 'Food & Dining',
  breakfast: 'Food & Dining',
  food: 'Food & Dining',
  pizza: 'Food & Dining',
  burger: 'Food & Dining',
  swiggy: 'Food & Dining',
  zomato: 'Food & Dining',
  restaurant: 'Food & Dining',
  snacks: 'Food & Dining',
  biryani: 'Food & Dining',
  dosa: 'Food & Dining',
  petrol: 'Transportation',
  diesel: 'Transportation',
  fuel: 'Transportation',
  uber: 'Transportation',
  ola: 'Transportation',
  auto: 'Transportation',
  bus: 'Transportation',
  metro: 'Transportation',
  train: 'Transportation',
  taxi: 'Transportation',
  cab: 'Transportation',
  parking: 'Transportation',
  toll: 'Transportation',
  grocery: 'Groceries',
  groceries: 'Groceries',
  milk: 'Groceries',
  vegetables: 'Groceries',
  fruits: 'Groceries',
  supermarket: 'Groceries',
  bigbasket: 'Groceries',
  dmart: 'Groceries',
  meat: 'Groceries',
  fish: 'Groceries',
  electricity: 'Utilities',
  water: 'Utilities',
  gas: 'Utilities',
  wifi: 'Utilities',
  internet: 'Utilities',
  phone: 'Utilities',
  mobile: 'Utilities',
  recharge: 'Utilities',
  rent: 'Housing',
  maintenance: 'Housing',
  society: 'Housing',
  netflix: 'Entertainment',
  prime: 'Entertainment',
  hotstar: 'Entertainment',
  spotify: 'Entertainment',
  youtube: 'Entertainment',
  movie: 'Entertainment',
  movies: 'Entertainment',
  cinema: 'Entertainment',
  game: 'Entertainment',
  gaming: 'Entertainment',
  medical: 'Healthcare',
  doctor: 'Healthcare',
  hospital: 'Healthcare',
  medicine: 'Healthcare',
  pharmacy: 'Healthcare',
  clinic: 'Healthcare',
  gym: 'Healthcare',
  fitness: 'Healthcare',
  cloth: 'Shopping',
  clothes: 'Shopping',
  dress: 'Shopping',
  shoes: 'Shopping',
  amazon: 'Shopping',
  flipkart: 'Shopping',
  myntra: 'Shopping',
  mall: 'Shopping',
  subscription: 'Subscription',
  subscribe: 'Subscription',
  renewal: 'Subscription',
  renew: 'Subscription',
  salary: 'Income',
  freelance: 'Income',
  freelancing: 'Income',
  business: 'Income',
  interest: 'Income',
  dividend: 'Income',
  refund: 'Income',
  cashback: 'Income',
  emi: 'EMI',
  loan: 'EMI',
  insurance: 'Insurance',
  premium: 'Insurance',
  gift: 'Gifts & Rewards',
  donation: 'Gifts & Rewards',
};
