export type DarkPalette = typeof palette.dark;
export type LightPalette = typeof palette.light;

export const palette = {
  white: '#FFFFFF',
  black: '#000000',
  transparent: 'transparent',

  // ── BRAND: VIBRANT VIOLET ─────────────────────────────────
  brand: {
    primary: '#7C3AED',
    secondary: '#8B5CF6',
    light: '#A78BFA',
    ultraLight: '#EDE9FE',
    dark: '#5B21B6',
    hover: '#5B21B6',
    muted: '#A78BFA',
  },

  // ── LIGHT ─────────────────────────────────────────────────
  light: {
    bg: {
      primary: '#F8F8FA',
      secondary: '#FFFFFF',
      tertiary: '#F2F2F7',
      card: '#FFFFFF',
      elevated: '#FFFFFF',
      highlight: '#7C3AED12',
      overlay: 'rgba(0, 0, 0, 0.20)',
      glass: '#F2F2F7',
      glassLight: '#FFFFFF',
    },
    card: {
      balance: '#F5F3FF',
      income: '#F0FDF4',
      expense: '#FEF2F2',
      savings: '#F5F3FF',
      budget: '#FFFFFF',
      default: '#FFFFFF',
    },
    text: {
      primary: '#111827',
      secondary: '#6B7280',
      tertiary: '#9CA3AF',
      inverse: '#FFFFFF',
      link: '#7C3AED',
      success: '#22C55E',
    },
    brand: {
      primary: '#7C3AED',
      light: '#EDE9FE',
      hover: '#6D28D9',
      muted: '#A78BFA',
    },
    border: {
      subtle: '#E5E7EB',
      default: '#D1D5DB',
      active: '#7C3AED40',
    },
    accent: {
      primary: '#7C3AED',
      secondary: '#8B5CF6',
      tertiary: '#A78BFA',
      hover: '#6D28D9',
    },
    status: {
      success: '#22C55E',
      successLight: '#F0FDF4',
      warning: '#F59E0B',
      warningLight: '#FFFBEB',
      error: '#EF4444',
      errorLight: '#FEF2F2',
      info: '#7C3AED',
      infoLight: '#F5F3FF',
    },
    chart: {
      netWorth: '#7C3AED',
      income: '#22C55E',
      expense: '#EF4444',
      goals: '#F59E0B',
    },
    skeleton: {
      base: '#E5E7EB',
      highlight: '#F3F4F6',
    },
    shadow: 'rgba(0, 0, 0, 0.06)',
  },

  // ── DARK ──────────────────────────────────────────────────
  dark: {
    bg: {
      primary: '#0A0A0A',
      secondary: '#111111',
      tertiary: '#1C1C1E',
      card: '#1C1C1E',
      elevated: '#2C2C2E',
      highlight: '#7C3AED20',
      overlay: 'rgba(0, 0, 0, 0.75)',
      glass: '#111111',
      glassLight: '#1C1C1E',
    },
    card: {
      balance: '#1E1B4B',
      income: '#052E16',
      expense: '#2D0A0A',
      savings: '#1E1B4B',
      budget: '#1C1C1E',
      default: '#1C1C1E',
    },
    text: {
      primary: '#F9FAFB',
      secondary: '#9CA3AF',
      tertiary: '#6B7280',
      inverse: '#111827',
      link: '#A78BFA',
      success: '#4ADE80',
    },
    brand: {
      primary: '#A78BFA',
      light: '#2E1065',
      hover: '#8B5CF6',
      muted: '#7C3AED',
    },
    border: {
      subtle: '#27272A',
      default: '#3F3F46',
      active: '#A78BFA50',
    },
    accent: {
      primary: '#A78BFA',
      secondary: '#8B5CF6',
      tertiary: '#7C3AED',
      hover: '#C4B5FD',
    },
    status: {
      success: '#4ADE80',
      successLight: '#052E16',
      warning: '#FBBF24',
      warningLight: '#422006',
      error: '#F87171',
      errorLight: '#3B0A0A',
      info: '#A78BFA',
      infoLight: '#1E1B4B',
    },
    chart: {
      netWorth: '#A78BFA',
      income: '#4ADE80',
      expense: '#F87171',
      goals: '#FBBF24',
    },
    skeleton: {
      base: '#27272A',
      highlight: '#3F3F46',
    },
    shadow: 'rgba(0, 0, 0, 0.45)',
  },

  // ── COUPLE LIGHT ──────────────────────────────────────────
  coupleLight: {
    bg: {
      primary: '#FFF5F7',
      secondary: '#FFFFFF',
      tertiary: '#FFF5F7',
      card: '#FFFFFF',
      elevated: '#FFFFFF',
      highlight: '#F43F5E12',
      overlay: 'rgba(0, 0, 0, 0.20)',
      glass: '#FFF5F7',
      glassLight: '#FFFFFF',
    },
    card: {
      balance: '#FFF0F3',
      income: '#F0FDF4',
      expense: '#FEF2F2',
      savings: '#FFF0F3',
      budget: '#FFFFFF',
      default: '#FFFFFF',
    },
    text: {
      primary: '#111827',
      secondary: '#6B7280',
      tertiary: '#9CA3AF',
      inverse: '#FFFFFF',
      link: '#F43F5E',
      success: '#22C55E',
    },
    brand: {
      primary: '#F43F5E',
      light: '#FFF0F3',
      hover: '#E11D48',
      muted: '#FB7185',
    },
    border: {
      subtle: '#E5E7EB',
      default: '#D1D5DB',
      active: '#F43F5E40',
    },
    accent: {
      primary: '#F43F5E',
      secondary: '#FB7185',
      tertiary: '#FDA4AF',
      hover: '#E11D48',
    },
    status: {
      success: '#22C55E',
      successLight: '#F0FDF4',
      warning: '#F59E0B',
      warningLight: '#FFFBEB',
      error: '#EF4444',
      errorLight: '#FEF2F2',
      info: '#F43F5E',
      infoLight: '#FFF0F3',
    },
    chart: {
      line1: '#F43F5E',
      line2: '#22C55E',
      line3: '#F59E0B',
      line4: '#EF4444',
    },
    skeleton: {
      base: '#E5E7EB',
      highlight: '#FFF5F7',
    },
    shadow: 'rgba(244, 63, 94, 0.08)',
  },

  // ── COUPLE DARK ───────────────────────────────────────────
  coupleDark: {
    bg: {
      primary: '#0A0A0A',
      secondary: '#111111',
      tertiary: '#1C1C1E',
      card: '#1C1C1E',
      elevated: '#2C2C2E',
      highlight: '#F43F5E20',
      overlay: 'rgba(0, 0, 0, 0.75)',
      glass: '#111111',
      glassLight: '#1C1C1E',
    },
    card: {
      balance: '#2D0A16',
      income: '#052E16',
      expense: '#2D0A0A',
      savings: '#1E0A1E',
      budget: '#1C1C1E',
      default: '#1C1C1E',
    },
    text: {
      primary: '#F9FAFB',
      secondary: '#9CA3AF',
      tertiary: '#6B7280',
      inverse: '#111827',
      link: '#FB7185',
      success: '#4ADE80',
    },
    brand: {
      primary: '#FB7185',
      light: '#2D0A16',
      hover: '#F43F5E',
      muted: '#FDA4AF',
    },
    border: {
      subtle: '#27272A',
      default: '#3F3F46',
      active: '#FB718550',
    },
    accent: {
      primary: '#FB7185',
      secondary: '#FDA4AF',
      tertiary: '#FECDD3',
      hover: '#F43F5E',
    },
    status: {
      success: '#4ADE80',
      successLight: '#052E16',
      warning: '#FBBF24',
      warningLight: '#422006',
      error: '#F87171',
      errorLight: '#3B0A0A',
      info: '#FB7185',
      infoLight: '#2D0A16',
    },
    chart: {
      line1: '#FB7185',
      line2: '#4ADE80',
      line3: '#FBBF24',
      line4: '#F87171',
    },
    skeleton: {
      base: '#27272A',
      highlight: '#3F3F46',
    },
    shadow: 'rgba(0, 0, 0, 0.45)',
  },
} as const;
